db.driver = com.mysql.cj.jdbc.Driver
user = b263e859015477
password = 3d881422
db.url = us-cdbr-east-04.cleardb.com
useUnicode = true
encoding = UTF-8
useSSL = false

allowPublicKeyRetrieval = true

useJDBCCompliantTimezoneShift = true
useLegacyDatetimeCode = false
serverTimezone = UTC

mysql://b263e859015477:3d881422@us-cdbr-east-04.cleardb.com/heroku_05bb384fd3ec211?reconnect=true